name: nuget publish

on: 
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Git Version
      id: version
      uses: codacy/git-version@2.4.0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --no-restore

    - name: dotnet pack
      run: dotnet pack --no-restore -c Release --include-source --include-symbols -p:PackageVersion='${{ steps.version.outputs.version }}'
